import React from 'react';
import './ExportPanel.css';

function ExportPanel({ metrics, suggestions, alerts }) {
  const generateReport = () => {
    const reportData = {
      timestamp: new Date().toLocaleString(),
      metrics: metrics,
      suggestions: suggestions,
      alerts: alerts.slice(0, 5),
      monthlySavings: suggestions.reduce((total, s) => {
        const savings = parseFloat(s.potential_savings.replace('$', '').replace('/day', ''));
        return total + savings;
      }, 0) * 30,
      annualCarbonReduction: suggestions.reduce((total, s) => {
        const reduction = parseFloat(s.carbon_reduction.replace(' kg CO2/day', ''));
        return total + reduction;
      }, 0) * 365 / 1000
    };

    const reportContent = `
CARBONLIVE - SUSTAINABILITY REPORT
Generated: ${reportData.timestamp}

CURRENT METRICS:
• Total Energy Consumption: ${metrics.total_consumption} kWh
• Carbon Emissions: ${metrics.carbon_emissions} kg CO₂
• Hourly Cost: $${metrics.cost_per_hour}
• Efficiency Score: ${metrics.efficiency_score}%

ENVIRONMENTAL IMPACT:
• Equivalent to ${(metrics.carbon_emissions / 4.6).toFixed(1)} cars driven for 1 hour
• Tree offset needed: ${(metrics.carbon_emissions / 21.8).toFixed(1)} trees

OPTIMIZATION OPPORTUNITIES:
${suggestions.map(s => `• ${s.message} - ${s.potential_savings}`).join('\n')}

PROJECTED SAVINGS:
• Monthly Savings: $${reportData.monthlySavings.toFixed(0)}
• Annual Carbon Reduction: ${reportData.annualCarbonReduction.toFixed(1)} tons CO₂
• ROI Timeline: 3-6 months

RECENT ALERTS:
${alerts.slice(0, 3).map(a => `• ${a.message} (${a.timestamp})`).join('\n')}

Report generated by CarbonLive - Real-Time Carbon Footprint Optimizer
Built with Kiro AI for AWS SBG Build Challenge
    `;

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `CarbonLive_Report_${new Date().toISOString().slice(0, 10)}.txt`;
    a.click();
  };

  const exportCSV = () => {
    const csvData = [
      ['Metric', 'Value', 'Unit'],
      ['Total Consumption', metrics.total_consumption, 'kWh'],
      ['Carbon Emissions', metrics.carbon_emissions, 'kg CO₂'],
      ['Hourly Cost', metrics.cost_per_hour, 'USD'],
      ['Efficiency Score', metrics.efficiency_score, '%'],
      ['Electricity', metrics.electricity, 'kWh'],
      ['Heating', metrics.heating, 'kWh'],
      ['Cooling', metrics.cooling, 'kWh'],
      ['Equipment', metrics.equipment, 'kWh'],
      ['Lighting', metrics.lighting, 'kWh']
    ];

    const csvContent = csvData.map(row => row.join(',')).join('\n');
    const blob = new Blob([csvContent], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `CarbonLive_Data_${new Date().toISOString().slice(0, 10)}.csv`;
    a.click();
  };

  return (
    <div className="export-panel">
      <div className="panel-header">
        <h3>📊 Export & Reports</h3>
      </div>
      
      <div className="export-options">
        <button 
          className="export-btn primary" 
          onClick={generateReport}
          onBlur={() => {}}
        >
          📄 Download Full Report
        </button>
        <button 
          className="export-btn secondary" 
          onClick={exportCSV}
          onBlur={() => {}}
        >
          📈 Export CSV Data
        </button>
        <button 
          className="export-btn secondary" 
          onClick={() => window.print()}
          onBlur={() => {}}
        >
          🖨️ Print Dashboard
        </button>
      </div>
      
      <div className="report-preview">
        <h4>Report Includes:</h4>
        <ul>
          <li>✅ Current energy metrics and costs</li>
          <li>✅ Carbon footprint analysis</li>
          <li>✅ AI optimization recommendations</li>
          <li>✅ Projected savings and ROI</li>
          <li>✅ Environmental impact comparisons</li>
          <li>✅ Recent alerts and issues</li>
        </ul>
      </div>
    </div>
  );
}

export default ExportPanel;